# ------------------------------------------
# SPDX-License-Identifier: MIT OR Apache-2.0
# ------------------------------------------
[profile.default]
slow-timeout = { period = "1s", terminate-after = 3 }
