name: Generate codecov

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  MISE_ENV: ci
  RUSTFLAGS: -Zcodegen-backend=llvm

jobs:
  generate-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [q_screens, q_cmd_prompt, q_test_harness]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{matrix.package}}-ci-${{ hashFiles('**/Cargo.toml') }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        if: ${{contains(env.RUSTC_WRAPPER, 'sccache')}}

      - name: Install dependencies
        shell: bash
        run: >
          sudo apt-get update;
          sudo apt-get install -y --no-install-recommends
          libasound2-dev
          libudev-dev
          libwayland-dev
          ;

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-12-11
          components: rustc-dev,llvm-tools-preview

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Collect coverage data
        run: cargo llvm-cov nextest -p ${{ matrix.package }} --lcov --output-path report.lcov

      - name: Upload to coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          parallel: true
          flag-name: ${{matrix.package}}
  finish:
    runs-on: ubuntu-latest
    needs: generate-coverage
    if: ${{always()}}
    steps:
      - name: Finish coveralls upload
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "q_screens,q_cmd_prompt,q_test_harness" # MUST MATCH ALL MATRIX VALUES
