name: Cargo Build & Test

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  MISE_ENV: ci
  RUSTFLAGS: -Zcodegen-backends=llvm

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
        package: [q_screens, q_cmd_prompt, q_test_harness]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-ci-${{ hashFiles('**/Cargo.toml') }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Install dependencies
        shell: bash
        run: >
          sudo apt-get update;
          sudo apt-get install -y --no-install-recommends
          libasound2-dev
          libudev-dev
          libwayland-dev
          ;

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-12-11
          components: rustc-dev,llvm-tools-preview

      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Collect coverage data
        run: cargo llvm-cov nextest -p ${{ matrix.package }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ada-x64/qproj
